hydra:
  job:
    chdir: True

env_name: box2d_bipedal_walker
algorithm: sac
landscape_only: true
dir: ${hydra:runtime.cwd}
data_dir: arlbench_data
repo_id: autorl-org/arlbench
benchmark: arlbench
num_configs: 256
num_seeds: 10
